### ISSUE TITLE
Sending Status command to device results in ValueError

### ISSUE THREAD

**Issue by timboring** [timboring/atlas_i2c#1]
Obviously `read()` needs to be smarter about parsing responses:

```py
>>> dev.query("Status")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tjb/.local/lib/python3.7/site-packages/atlas_i2c.py", line 106, in query
    return self.read()
  File "/home/tjb/.local/lib/python3.7/site-packages/atlas_i2c.py", line 89, in read
    result = float(data)
ValueError: could not convert string to float: b'?STATUS,P,5.02'
```

**Comment by timboring** [comment]
This is the same for any command that doesn't return a numeric value, i.e. "S,?", "i", etc.

**Comment by timboring** [comment]
I've refactored the code a bit that ultimately handles this bug.
